In [0]:
pip install emoji

In [0]:
import emoji

In [0]:
emoji.UNICODE_EMOJI

{'🥇': ':1st_place_medal:',
 '🥈': ':2nd_place_medal:',
 '🥉': ':3rd_place_medal:',
 '🆎': ':AB_button_(blood_type):',
 '🏧': ':ATM_sign:',
 '🅰': ':A_button_(blood_type):',
 '🇦🇫': ':Afghanistan:',
 '🇦🇱': ':Albania:',
 '🇩🇿': ':Algeria:',
 '🇦🇸': ':American_Samoa:',
 '🇦🇩': ':Andorra:',
 '🇦🇴': ':Angola:',
 '🇦🇮': ':Anguilla:',
 '🇦🇶': ':Antarctica:',
 '🇦🇬': ':Antigua_&_Barbuda:',
 '♒': ':Aquarius:',
 '🇦🇷': ':Argentina:',
 '♈': ':Aries:',
 '🇦🇲': ':Armenia:',
 '🇦🇼': ':Aruba:',
 '🇦🇨': ':Ascension_Island:',
 '🇦🇺': ':Australia:',
 '🇦🇹': ':Austria:',
 '🇦🇿': ':Azerbaijan:',
 '🔙': ':BACK_arrow:',
 '🅱': ':B_button_(blood_type):',
 '🇧🇸': ':Bahamas:',
 '🇧🇭': ':Bahrain:',
 '🇧🇩': ':Bangladesh:',
 '🇧🇧': ':Barbados:',
 '🇧🇾': ':Belarus:',
 '🇧🇪': ':Belgium:',
 '🇧🇿': ':Belize:',
 '🇧🇯': ':Benin:',
 '🇧🇲': ':Bermuda:',
 '🇧🇹': ':Bhutan:',
 '🇧🇴': ':Bolivia:',
 '🇧🇦': ':Bosnia_&_Herzegovina:',
 '🇧🇼': ':Botswana:',
 '🇧🇻': ':Bouvet_Island:',
 '🇧🇷': ':Brazil:',
 '🇮🇴': ':British_Indian_Ocean_Territory:',
 '🇻🇬': ':British_Vir

In [0]:
emojidict={"0": "\u2764\uFE0F",    # :heart: prints a black instead of red heart depending on the font
                    "1": ":baseball:",
                    "2": ":grinning_face_with_big_eyes:",
                    "3": ":disappointed_face:",
                    "4": ":fork_and_knife:",
                    "5": ":hundred_points:",
                    "6": ":fire:",
                    "7": ":face_blowing_a_kiss:",
                    "8": ":chestnut:",
                    "9":":flexed_biceps:"
                   }


In [0]:
for e in emojidict.values(): # printing some emoji
  print(emoji.emojize(e))

❤️
⚾
😃
😞
🍴
💯
🔥
😘
🌰
💪


In [0]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split


In [0]:
train=pd.read_csv("/content/drive/My Drive/twitter-emoji-prediction/train_emoji.csv")
test=pd.read_csv("/content/drive/My Drive/twitter-emoji-prediction/test_emoji.csv")

In [0]:
train.head(10)

never talk to me again  3  Unnamed: 2 Unnamed: 3
0     I am proud of your achievements  2         NaN        NaN
1      It is the worst day in my life  3         NaN        NaN
2                    Miss you so much  0         NaN        [0]
3                        food is life  4         NaN        NaN
4                      I love you mum  0         NaN        NaN
5                Stop saying bullshit  3         NaN        NaN
6  congratulations on your acceptance  2         NaN        NaN
7         The assignment is too long   3         NaN        NaN
8                   I want to go play  1         NaN        [3]
9         she did not answer my text   3         NaN        NaN

In [0]:
xtrain=train.values[:,0]
ytrain=train.values[:,1]

xtest=test.values[:,0]
ytest=test.values[:,1]
print(xtrain.shape,ytrain.shape,xtest.shape,ytest.shape)

(131,) (131,) (55,) (55,)


In [0]:
for i in range(10):
  print(xtrain[i],emoji.emojize(emojidict[str(ytrain[i])]))
  

I am proud of your achievements 😃
It is the worst day in my life 😞
Miss you so much ❤️
food is life 🍴
I love you mum ❤️
Stop saying bullshit 😞
congratulations on your acceptance 😃
The assignment is too long  😞
I want to go play ⚾
she did not answer my text  😞


In [0]:
emoji.emojize(emojidict[str(ytrain[0])])

'😃'

In [0]:
f=open("/content/drive/My Drive/glove6b50dtxt/glove.6B.50d.txt")

In [0]:
wordembed={}
for line in f:
  val=line.split()
  word=val[0]
  embed=np.asarray(val[1:],dtype='float32')
  wordembed[word]=embed

In [0]:
count=0
for e in wordembed.items():
  print(e)
  count+=1
  if count==3:
    break

('the', array([ 4.1800e-01,  2.4968e-01, -4.1242e-01,  1.2170e-01,  3.4527e-01,
       -4.4457e-02, -4.9688e-01, -1.7862e-01, -6.6023e-04, -6.5660e-01,
        2.7843e-01, -1.4767e-01, -5.5677e-01,  1.4658e-01, -9.5095e-03,
        1.1658e-02,  1.0204e-01, -1.2792e-01, -8.4430e-01, -1.2181e-01,
       -1.6801e-02, -3.3279e-01, -1.5520e-01, -2.3131e-01, -1.9181e-01,
       -1.8823e+00, -7.6746e-01,  9.9051e-02, -4.2125e-01, -1.9526e-01,
        4.0071e+00, -1.8594e-01, -5.2287e-01, -3.1681e-01,  5.9213e-04,
        7.4449e-03,  1.7778e-01, -1.5897e-01,  1.2041e-02, -5.4223e-02,
       -2.9871e-01, -1.5749e-01, -3.4758e-01, -4.5637e-02, -4.4251e-01,
        1.8785e-01,  2.7849e-03, -1.8411e-01, -1.1514e-01, -7.8581e-01],
      dtype=float32))
(',', array([ 0.013441,  0.23682 , -0.16899 ,  0.40951 ,  0.63812 ,  0.47709 ,
       -0.42852 , -0.55641 , -0.364   , -0.23938 ,  0.13001 , -0.063734,
       -0.39575 , -0.48162 ,  0.23291 ,  0.090201, -0.13324 ,  0.078639,
       -0.41634 , -0.154

In [0]:
for i in range(len(xtrain)):
  xtrain[i]=xtrain[i].split()
for i in range(len(xtest)):
  xtest[i]=xtest[i].split()




In [0]:
xtrain[0]

['I', 'am', 'proud', 'of', 'your', 'achievements']

In [0]:
from keras.utils import to_categorical

Using TensorFlow backend.


In [0]:
ytest=to_categorical(ytest)
ytrain=to_categorical(ytrain)

In [0]:
print(ytrain.shape)

(131, 5)


In [0]:
for line in xtrain:
  print(line)
  break
print(xtrain[0][0])

['I', 'am', 'proud', 'of', 'your', 'achievements']
I


In [0]:
def convert(dataset):
  maxlen=10
  vol=np.zeros((dataset.shape[0],maxlen,50))     # as each word is in 50 dims 
  for i  in range(len(dataset)):
    for j in range(len(line)):
      try:
        vol[i][j]=wordembed[dataset[i][j].lower()] # length upto 10 is considered
      except:
        vol[i][j]=np.zeros((50,)) # remaining  word are setted as zero
  return vol


In [0]:
xtrainemb=convert(xtrain)

In [0]:
xtestemb=convert(xtest)

In [0]:
print(xtrainemb.shape,xtestemb.shape)

(131, 10, 50) (55, 10, 50)


In [0]:
xtrainemb[0]

array([[ 1.18910000e-01,  1.52549997e-01, -8.20730031e-02,
        -7.41439998e-01,  7.59169996e-01, -4.83280003e-01,
        -3.10090005e-01,  5.14760017e-01, -9.87079978e-01,
         6.17570011e-04, -1.50429994e-01,  8.37700009e-01,
        -1.07969999e+00, -5.14599979e-01,  1.31879997e+00,
         6.20069981e-01,  1.37789994e-01,  4.71080005e-01,
        -7.28740022e-02, -7.26750016e-01, -7.41159976e-01,
         7.52629995e-01,  8.81799996e-01,  2.95610011e-01,
         1.35479999e+00, -2.57010007e+00, -1.35230005e+00,
         4.58799988e-01,  1.00680006e+00, -1.18560004e+00,
         3.47370005e+00,  7.78980017e-01, -7.29290009e-01,
         2.51020014e-01, -2.61559993e-01, -3.46839994e-01,
         5.58409989e-01,  7.50980020e-01,  4.98299986e-01,
        -2.68229991e-01, -2.74430006e-03, -1.82980001e-02,
        -2.80959994e-01,  5.53179979e-01,  3.77059989e-02,
         1.85550004e-01, -1.50250003e-01, -5.75119972e-01,
        -2.66710013e-01,  9.21209991e-01],
       [ 3.46

In [0]:
from tensorflow.python.keras.layers import Flatten,Dense,LSTM,Dropout,Activation
from tensorflow.python.keras.activations import softmax,relu,sigmoid
from tensorflow.python.keras.models import Sequential

In [0]:
model=Sequential()

model.add(LSTM(64,input_shape=(10,50),return_sequences=True,recurrent_dropout=0.1))
model.add(Dropout(0.2))

model.add(LSTM(64,input_shape=(10,50),return_sequences=False,recurrent_dropout=0.1))
model.add(Dropout(0.5))

model.add(Dense(20))
model.add(Activation('sigmoid'))

model.add(Dense(5))
model.add(Activation('softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 10, 64)            29440     
_________________________________________________________________
dropout (Dropout)            (None, 10, 64)            0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 64)                33024     
_________________________________________________________________
dropout_1 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense (Dense)                (None, 20)                1300      
_________________________________________________________________
activation (Activation)      (None, 20)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 1

In [0]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [0]:
model.fit(xtrainemb,ytrain,batch_size=20,epochs=50,validation_split=0.1)

Epoch 1/50
6/6 [==============================] - 1s 111ms/step - loss: 1.6244 - accuracy: 0.1624 - val_loss: 1.6195 - val_accuracy: 0.2143
Epoch 2/50
6/6 [==============================] - 0s 25ms/step - loss: 1.5882 - accuracy: 0.1538 - val_loss: 1.6381 - val_accuracy: 0.3571
Epoch 3/50
6/6 [==============================] - 0s 25ms/step - loss: 1.5495 - accuracy: 0.2821 - val_loss: 1.6712 - val_accuracy: 0.0714
Epoch 4/50
6/6 [==============================] - 0s 25ms/step - loss: 1.5274 - accuracy: 0.3162 - val_loss: 1.6733 - val_accuracy: 0.0714
Epoch 5/50
6/6 [==============================] - 0s 26ms/step - loss: 1.4947 - accuracy: 0.3504 - val_loss: 1.6615 - val_accuracy: 0.0714
Epoch 6/50
6/6 [==============================] - 0s 25ms/step - loss: 1.4436 - accuracy: 0.3932 - val_loss: 1.6187 - val_accuracy: 0.1429
Epoch 7/50
6/6 [==============================] - 0s 25ms/step - loss: 1.3756 - accuracy: 0.4957 - val_loss: 1.6366 - val_accuracy: 0.1429
Epoch 8/50
6/6 [==========

In [0]:
model.save("myemoji.h5")
from tensorflow.python.keras.callbacks import EarlyStopping,ModelCheckpoint

In [0]:
#cp=ModelCheckpoint("model.h5",monitor='val_loss',save_best_only=True,save_weights_only=False)

In [0]:
#es=EarlyStopping(monitor="val_acc",patience=2)

In [0]:
#model.fit(xtrainemb,ytrain,batch_size=20,epochs=50,validation_split=0.1,callbacks=[cp,es])

In [0]:
pred=model.predict_classes(xtestemb)

In [0]:
for i in range(xtest.shape):
  print(xtest[i], emoji.emojize(emojidict[str(ytest[i].argmax())])  )

TypeError: ignored

In [0]:
for i in range(10):
  print(xtest[i])
  print(emoji.emojize(emojidict[str(ytrain[i].argmax())]))
  print("-------------",emoji.emojize(emojidict[str(pred[i])]),"--------------")
  #print(emoji.emojize(emojidict[str(pred[i])]))


['he', 'did', 'not', 'answer']
😃
------------- 😞 --------------
['he', 'got', 'a', 'raise']
😞
------------- 😞 --------------
['she', 'got', 'me', 'a', 'present']
❤️
------------- ❤️ --------------
['ha', 'ha', 'ha', 'it', 'was', 'so', 'funny']
🍴
------------- 😃 --------------
['he', 'is', 'a', 'good', 'friend']
❤️
------------- 😃 --------------
['I', 'am', 'upset']
😞
------------- 😞 --------------
['We', 'had', 'such', 'a', 'lovely', 'dinner', 'tonight']
😃
------------- 😃 --------------
['where', 'is', 'the', 'food']
😞
------------- ⚾ --------------
['Stop', 'making', 'this', 'joke', 'ha', 'ha', 'ha']
⚾
------------- 😃 --------------
['where', 'is', 'the', 'ball']
😞
------------- ⚾ --------------


In [0]:
print(ytest.argmax())

3


In [0]:
realout=test.values[:,1]

In [0]:
realout

array([3, 2, 0, 2, 0, 0, 0, 4, 2, 1, 3, 3, 2, 1, 3, 3, 2, 3, 4, 0, 2, 4,
       3, 3, 3, 3, 0, 2, 0, 0, 1, 3, 2, 0, 1, 2, 4, 4, 2, 2, 2, 0, 1, 2,
       0, 2, 2, 2, 3, 3, 0, 3, 2, 2, 3], dtype=object)

In [0]:
pred

array([3, 3, 0, 2, 2, 3, 2, 1, 2, 1, 2, 0, 3, 1, 3, 3, 2, 3, 2, 0, 0, 4,
       0, 3, 3, 2, 0, 1, 2, 0, 1, 0, 2, 3, 1, 2, 3, 1, 2, 1, 0, 0, 1, 2,
       0, 3, 2, 3, 1, 3, 0, 3, 2, 3, 2])

In [0]:
acc=(realout==pred).sum()/realout.shape[0]

In [0]:
print(acc)

0.5454545454545454
